import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const HomePage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Benjamin Osmers</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to My Portfolio!</h1>

				<p className={styles.description}>This portfolio is still under construction.</p>
			</main>
		</div>
	)
}

export default HomePage
