import React from "react";
import styles from "../styles/Home.module.css";
import Head from "next/head";

const MindMaps = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MindMaps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>MindMaps!</h1>

        <div className={styles.grid}>
          <a href="./project_structure.html" className={styles.card}>
            <h2>Project Structure &rarr;</h2>
            <p>Overview of the project structure.</p>
          </a>
        </div>
        <div className={styles.grid}>
          <a href="./demo2.html" className={styles.card}>
            <h2>Demo 2 Summary &rarr;</h2>
            <p>Summmary of requirements for Demo 2.</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default MindMaps;
